version: '3'
services:
  db:
    image: mysql:8.0.25
    platform: linux/x86_64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: default
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1
      LANG: C.UTF-8
    ports:
      - 13316:3306

  redis:
    image: 'redis:6-alpine'
    platform: linux/x86_64
    ports:
      - 16389:6379

  app:
    build: .
    ports:
      - 4301:3000
    environment:
      # app
      - NODE_ENV=development
      - APP_NAME=chatbot
      - PORT=4301
      # database
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=1
      - DATABASE_NAME=default
      - DATABASE_LOG_ENABLE=true
      - DATABASE_LIMIT_CONNECTION=5
      # jwt
      - JWT_ACCESS_TOKEN_SECRET=access-secret
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=28800
      - JWT_REFRESH_TOKEN_SECRET=refresh-secret
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=604800
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
